# Welcome to the example configuration file!
# Remember that if this is in bin/Content.Server or such, it may be overwritten on build.
# Consider copying it and using the --config-file and --data-dir options.

[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = false

[net]
tickrate = 30
port = 1212
bindto = "::,0.0.0.0"
max_connections = 32
upnp = true

[status]
enabled = true
# bind = "brrr brrr patapim"
# connectaddress = "udp://localhost:1212"

[game]
hostname = "[RU][18+]👻Freaky Station 14👻[IN DEV]"
desc = "\n👻Freaky Station - Сервер с свободным отыгрышем РП.\n❗За основу на сервере взята сборка goob station, переведенная на русский язык. \n👇👇👇👇👇👇 На нашем сервере имеется:\n╭\n┊ 🩸 Продвинутая система хирургии и ранений. Теперь вы можете удалить вульпе хвост, или отрезать ей ноги.\n┊ 🤬 Множество новых антагонистов, например блоб, еретик, генокрад, абдуктор и даже халк!!.\n┊ 🤯 Большое количество разных мехов, как боевых, так и не боевых.\n┊ 🥵 Своя ерп панель, а так-же множество предметов для более качественного ерп отыгрыша, если вам хочется\n┊ 🪖 Огромное количество нового оружия, от самодельных мечей до лазерных пулеметов.\n┊ 🫑 И КОНЕЧНО ЖЕ САМЫЙ МОЩНЫЙ ХОСТ!!!\n┊ 🪐 И многое другое! Заходи и прощупай весь контент самостоятельно.\n╰"
peaceful_end = false
soft_max_players = 32
cryo_sleep_rejoining = true
panic_bunker.disable_with_admins = true
panic_bunker.enable_without_admins = true
panic_bunker.show_reason = true
panic_bunker.min_account_age = 800
panic_bunker.min_overall_minutes = 60
panic_bunker.custom_reason = "Админы спят. Заходите набегать/играть чуточку попозже. С любовью, ваши Freaky"

[console]
loginlocal = false
login_host_user = "Egorql"

[hub]
advertise = true
tags = "lang:ru,18+"
server_url = ""
hub_urls = "https://hub.spacestation14.com/"


[auth]
mode = 1

[infolinks]
discord = "https://discord.gg/BQHQNbuVCZ"
github = "https://github.com/Egorql/Freaky-Station"

[atmos]
space_wind = true

[ic]
flavor_text = true

[server]
rules_file = "FreakyRuleset"
lobby_name = "[RU][18+]Freaky Station 14[IN DEV]"

[shuttle]
emergency_early_launch_allowed = false
# arrivals = true
# arrivals_map = true
arrivals_planet = false

[vote]
map_enabled = true
restart_required_ratio = 0.65
timermap = 45

[admin]
deadmin_on_join = true 
new_player_join_sound = true

[looc]
enabled_crit = true

